name: cv_builder
description: "A new Flutter project."

publish_to: 'none'

version: 1.15.0+34

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_storage: ^12.4.0

  cpf_cnpj_validator: ^2.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  faker: ^2.2.0
  flutter_feather_icons: ^2.0.0
  flutter_svg: ^2.0.16
  image_picker: ^1.1.2
  # logging: ^1.3.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.13.4
  result_dart: ^2.0.0
  shared_preferences: ^2.3.4
  syncfusion_flutter_pdfviewer: ^28.1.37
  # timeago: ^3.7.0
  uuid: ^4.5.1  
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  get_it: ^8.0.3
  provider: ^6.1.2
  intl: ^0.19.0
  google_sign_in: ^6.2.2
  flutter_keyboard_visibility: ^6.0.0
  image: ^4.5.2
  image_cropper: ^9.0.0
  dropdown_search: ^6.0.2
  # carousel_slider: ^5.0.0
  firebase_crashlytics: ^4.3.4
  firebase_analytics: ^11.4.4
  package_info_plus: ^8.3.0
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  flutter_flavor: ^3.1.4
  dio: ^5.8.0+1
  share_plus: ^11.0.0
  file_picker: ^10.1.9
  # flutter_colorpicker: ^1.1.0

dev_dependencies:
  commitlint_cli: ^0.8.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  husky: ^0.1.7
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/brands/

  fonts:
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-Black.ttf
          weight: 800
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/config/splash.png"
  android: true
  ios: true
  web: false
  android_12:
    image: "assets/config/android_12_splash.png"
    color: "#FFFFFF"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/config/launcher.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/config/launcher.png"
  min_sdk_android: 21
  remove_alpha_ios: true
