name: cv_builder
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cloud_firestore: ^5.6.0
  cpf_cnpj_validator: ^2.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  faker: ^2.2.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter_feather_icons: ^2.0.0
  flutter_svg: ^2.0.16
  go_router: ^14.6.2
  image_picker: ^1.1.2
  intl: any
  logging: ^1.3.0
  path_provider: ^2.1.5
  pdf: ^3.11.1
  printing: ^5.13.4
  provider: ^6.1.2
  result_dart: ^2.0.0
  shared_preferences: ^2.3.4
  syncfusion_flutter_pdfviewer: ^28.1.37
  timeago: ^3.7.0
  uuid: ^4.5.1  
  modal_bottom_sheet: ^3.0.0
  firebase_storage: ^12.4.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Black.ttf
          weight: 700
