// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJYDT_knSg1cPUdSQqMMyFPiYzMz_vukM',
    appId: '1:643458092980:web:27331b5b145f3ca8c72ce1',
    messagingSenderId: '643458092980',
    projectId: 'cvbuilder-67b67',
    authDomain: 'cvbuilder-67b67.firebaseapp.com',
    storageBucket: 'cvbuilder-67b67.firebasestorage.app',
    measurementId: 'G-MCP7MNQ75W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrkRmofrls5bRMjHf_1eowv7AW67-v1iY',
    appId: '1:643458092980:android:68f94f9809f8fe5ac72ce1',
    messagingSenderId: '643458092980',
    projectId: 'cvbuilder-67b67',
    storageBucket: 'cvbuilder-67b67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiVIIBtTpNu6QAEvxiXWb6mllJ8gZndAs',
    appId: '1:643458092980:ios:b36e362538528254c72ce1',
    messagingSenderId: '643458092980',
    projectId: 'cvbuilder-67b67',
    storageBucket: 'cvbuilder-67b67.firebasestorage.app',
    iosBundleId: 'com.carvalhodev.cvbuilder.cvBuilder',
  );
}
